alter database add logfile group 4 ('+DATA2') size 1g;
alter database add logfile group 5 ('+DATA2') size 1g;
alter database add logfile group 6 ('+DATA2') size 1g;
alter system switch logfile;
alter system switch logfile;
alter system switch logfile;
alter system checkpoint;
alter database drop logfile group 1;
alter database drop logfile group 2;
alter database drop logfile group 3;
